// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServerAppFinalProject.Models;

namespace WebServerAppFinalProject.Migrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebServerAppFinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Cakes"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Cookies"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Bread"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Pies & Tarts"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Crips, Crumbles & Cobblers"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Brownies & Bars"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Frostings, Fillings & Jams"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Sweet Dough"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Pastry"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("WebServerAppFinalProject.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("Difficulty")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("RecipeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 1,
                            Difficulty = 2,
                            Name = "Chocolate Cake",
                            RecipeUrl = "https://www.noracooks.com/vegan-chocolate-cake/",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 2,
                            Difficulty = 1,
                            Name = "Chocolate Chip Cookies",
                            RecipeUrl = "https://www.noracooks.com/vegan-chocolate-chip-cookies/",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 1,
                            Difficulty = 2,
                            Name = "Carrot Cake with Cream Cheese Icing",
                            RecipeUrl = "https://lovingitvegan.com/vegan-carrot-cake-lemon-buttercream-frosting/",
                            SeasonId = 3
                        },
                        new
                        {
                            RecipeId = 4,
                            CategoryId = 4,
                            Difficulty = 3,
                            Name = "Apple Pie",
                            RecipeUrl = "https://www.gretchensveganbakery.com/the-best-apple-pie-recipe/",
                            SeasonId = 4
                        },
                        new
                        {
                            RecipeId = 5,
                            CategoryId = 2,
                            Difficulty = 2,
                            Name = "S'more Cookies",
                            RecipeUrl = "https://www.hotforfoodblog.com/recipes/2014/08/09/smore-cookies/",
                            SeasonId = 6
                        },
                        new
                        {
                            RecipeId = 6,
                            CategoryId = 8,
                            Difficulty = 3,
                            Name = "King Cake",
                            RecipeUrl = "https://foodwithfeeling.com/vegan-king-cake/",
                            SeasonId = 3
                        },
                        new
                        {
                            RecipeId = 7,
                            CategoryId = 1,
                            Difficulty = 2,
                            Name = "Zombie Brain Cupcakes",
                            RecipeUrl = "https://www.bearplate.com/vegan-zombie-brain-cupcakes/",
                            SeasonId = 5
                        },
                        new
                        {
                            RecipeId = 8,
                            CategoryId = 1,
                            Difficulty = 2,
                            Name = "Strawberry Lemondade Cupcakes",
                            RecipeUrl = "https://www.theppk.com/2020/05/strawberry-lemonade-cupcakes/",
                            SeasonId = 3
                        },
                        new
                        {
                            RecipeId = 9,
                            CategoryId = 2,
                            Difficulty = 1,
                            Name = "Sugar Cookies",
                            RecipeUrl = "https://www.noracooks.com/vegan-sugar-cookies/",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 10,
                            CategoryId = 9,
                            Difficulty = 5,
                            Name = "Croissants",
                            RecipeUrl = "http://www.marystestkitchen.com/how-to-make-vegan-croissants/",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 11,
                            CategoryId = 7,
                            Difficulty = 3,
                            Name = "Swiss Meringue Buttercream",
                            RecipeUrl = "https://www.gretchensveganbakery.com/aquafaba-swiss-buttercream-recipe/",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 12,
                            CategoryId = 9,
                            Difficulty = 4,
                            Name = "French Macarons",
                            RecipeUrl = "https://www.youtube.com/watch?v=fKGDtUruRqE&t=271s",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 13,
                            CategoryId = 8,
                            Difficulty = 3,
                            Name = "Hot Cross Buns",
                            RecipeUrl = "https://www.avantgardevegan.com/recipes/hot-cross-vegan-buns/",
                            SeasonId = 3
                        },
                        new
                        {
                            RecipeId = 14,
                            CategoryId = 10,
                            Difficulty = 3,
                            Name = "Aquafaba Christmas Tree Meringues",
                            RecipeUrl = "https://projectveganbaking.com/aquafaba-christmas-tree-meringues/",
                            SeasonId = 2
                        },
                        new
                        {
                            RecipeId = 15,
                            CategoryId = 2,
                            Difficulty = 4,
                            Name = "Pumpkin Roll",
                            RecipeUrl = "https://makeitdairyfree.com/vegan-pumpkin-roll/",
                            SeasonId = 4
                        },
                        new
                        {
                            RecipeId = 16,
                            CategoryId = 2,
                            Difficulty = 1,
                            Name = "Chocolate Peppermint Crinkle Cookies",
                            RecipeUrl = "https://www.mydarlingvegan.com/chocolate-peppermint-crinkle-cookies/",
                            SeasonId = 2
                        },
                        new
                        {
                            RecipeId = 17,
                            CategoryId = 3,
                            Difficulty = 2,
                            Name = "Rosemary Focaccia",
                            RecipeUrl = "https://www.gimmesomeoven.com/rosemary-focaccia-bread/",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 18,
                            CategoryId = 8,
                            Difficulty = 3,
                            Name = "Cinnamon Rolls",
                            RecipeUrl = "https://tasty.co/recipe/the-best-ever-vegan-cinnamon-rolls",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 19,
                            CategoryId = 1,
                            Difficulty = 1,
                            Name = "Victoria Sponge",
                            RecipeUrl = "https://veggiedesserts.com/vegan-victoria-sponge-recipe/",
                            SeasonId = 6
                        },
                        new
                        {
                            RecipeId = 20,
                            CategoryId = 9,
                            Difficulty = 4,
                            Name = "Pavlova",
                            RecipeUrl = "https://projectveganbaking.com/vegan-pavlova/",
                            SeasonId = 6
                        },
                        new
                        {
                            RecipeId = 21,
                            CategoryId = 6,
                            Difficulty = 2,
                            Name = "Salted Caramel Brownie",
                            RecipeUrl = "https://tasty.co/recipe/the-best-ever-vegan-cinnamon-rolls",
                            SeasonId = 1
                        },
                        new
                        {
                            RecipeId = 22,
                            CategoryId = 4,
                            Difficulty = 3,
                            Name = "Lemon Meringue Pie",
                            RecipeUrl = "https://tasty.co/recipe/the-best-ever-vegan-cinnamon-rolls",
                            SeasonId = 3
                        });
                });

            modelBuilder.Entity("WebServerAppFinalProject.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            SeasonId = 1,
                            Name = "General"
                        },
                        new
                        {
                            SeasonId = 2,
                            Name = "Year End Holidays"
                        },
                        new
                        {
                            SeasonId = 3,
                            Name = "Spring"
                        },
                        new
                        {
                            SeasonId = 4,
                            Name = "Fall & Thanksgiving"
                        },
                        new
                        {
                            SeasonId = 5,
                            Name = "Halloween"
                        },
                        new
                        {
                            SeasonId = 6,
                            Name = "Summer"
                        },
                        new
                        {
                            SeasonId = 7,
                            Name = "Valentine's Day"
                        });
                });

            modelBuilder.Entity("WebServerAppFinalProject.Models.Recipe", b =>
                {
                    b.HasOne("WebServerAppFinalProject.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebServerAppFinalProject.Models.Season", "Season")
                        .WithMany("Recipes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
